import type { Grade } from "./types";

export const hdpeGrades: Grade[] = [
  {
    id: "hd-t9",
    name: "HD T9",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Raffia / Stretched Tape",
    summary:
      "HDPE stretched tape / raffia grade with excellent processability and mechanical strength.",
    applications: "Stretched tape / raffia for woven fabrics and tarpaulin",
    bis: "IS 7328-3B-TB-EDA",
    mfi: "1.1",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.1" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "27" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "26" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "11" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "1100" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "400" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1100" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "127" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "133" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "61" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 240 °C" },
      { label: "Die Temperature", value: "230 – 250 °C" },
      { label: "Quench Temperature", value: "30 °C" },
    ],
    flags: ["Food contact", "IS 7328:2020"],
  },
  {
    id: "hd-t10",
    name: "HD T10",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Yarn / Monofilament",
    summary:
      "HDPE yarn / monofilament grade with excellent processability and mechanical strength.",
    applications: "Yarns / monofilament for fabrics, nets, twines and ropes",
    bis: "IS 7328-3B-LBO-EDA",
    mfi: "1.1",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.1" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "27" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "26" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "11" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "1100" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "400" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "127" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "133" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "61" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 240 °C" },
      { label: "Die Temperature", value: "230 – 250 °C" },
      { label: "Quench Temperature", value: "30 °C" },
      { label: "Stretching Temperature", value: "95 – 120 °C" },
    ],
    flags: ["Food contact", "IS 7328:2020"],
  },
  {
    id: "hd-t10s",
    name: "HD T10S",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Monofilament",
    summary:
      "HDPE monofilament grade with excellent processability and mechanical strength.",
    applications: "Monofilament for nets, twines and ropes",
    bis: "IS 7328-3B-LB-EDA",
    mfi: "1.1",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.1" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "27" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "26" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "11" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "1100" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "400" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "127" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "61" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 240 °C" },
      { label: "Die Temperature", value: "230 – 250 °C" },
      { label: "Quench Temperature", value: "30 °C" },
      { label: "Stretching Temperature", value: "~ 98 °C (Water)" },
    ],
    flags: ["Food contact", "IS 7328:2020"],
  },
  {
    id: "m5002l",
    name: "M5002L",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Injection / Caps & Closures",
    summary:
      "Narrow MWD HDPE for injection and extrusion-compression molded caps & closures. Superior processability, excellent organoleptics.",
    applications: "Injection and extrusion-compression molded caps & closures",
    bis: "IS 7328-3B-CB-EDB",
    mfi: "3",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "8" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "70" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "30" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "180" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "950" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "70" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "132" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "61" },
    ],
    processing: [{ label: "Barrel Temperature", value: "160 – 190 °C" }],
    flags: ["Food contact", "Narrow MWD", "Organoleptics"],
  },
  {
    id: "m5005l",
    name: "M5005L",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Injection Molding",
    summary:
      "Narrow MWD HDPE for heavy-duty crates, industrial products, and caps for packaged drinking water.",
    applications:
      "Heavy-duty crates, industrial products, injection / ECM caps for packaged drinking water",
    bis: "IS 7328-3B-MB-EDC",
    mfi: "4.5",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "4.5" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "10" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "110" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "22" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "31" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "100" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "850" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "70" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "124" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "132" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "62" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "185 – 235 °C" },
      { label: "Nozzle Temperature", value: "235 °C" },
    ],
    flags: ["Food contact", "Narrow MWD", "Crates"],
  },
  {
    id: "m5018l",
    name: "M5018L",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Injection Molding",
    summary: "General-purpose injection molding HDPE combining excellent processability with good mechanical properties.",
    applications: "General purpose injection molding",
    bis: "IS 7328-3B-MB-EDE",
    mfi: "20",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "20" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "50" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "450" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "22" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "10" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "450" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "35" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "800" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "64" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "121" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "132" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "62" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 235 °C" },
      { label: "Nozzle Temperature", value: "235 °C" },
    ],
    flags: ["Food contact", "High flow"],
  },
  {
    id: "m5025l",
    name: "M5025L",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Injection / Masterbatch",
    summary:
      "High-flow injection molding HDPE for general-purpose items and masterbatch applications.",
    applications: "General purpose injection molded items and masterbatch",
    mfi: "30.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "30.0" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "20" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "250" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "28" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "800" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "62" },
      { label: "Spiral Flow Length @ 235°C", method: "HPL Method", unit: "mm", value: "730" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "77" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "132" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 235 °C" },
      { label: "Nozzle Temperature", value: "235 °C" },
    ],
    flags: ["High flow", "Masterbatch"],
  },
  {
    id: "m6007l",
    name: "M6007L",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Injection Molding",
    summary:
      "Narrow MWD HDPE ideally suited for injection molding of heavy-duty crates and industrial products.",
    applications: "Heavy-duty crates and industrial products",
    bis: "IS 7328-3B-MB-EDD",
    mfi: "7.5",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "7.5" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "22" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "190" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "24" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "750" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "50" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "850" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "67" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "122" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "132" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "62" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "185 – 235 °C" },
      { label: "Nozzle Temperature", value: "200 – 235 °C" },
    ],
    flags: ["Food contact", "Narrow MWD", "Crates"],
  },
  {
    id: "m6007lu",
    name: "M6007LU",
    family: "HDPE",
    brand: "Halene H",
    technology: "Spherilene",
    category: "Injection Molding (UV)",
    summary:
      "UV-stabilized (HALS ~2000 ppm) narrow MWD HDPE for outdoor crates and industrial products.",
    applications: "Heavy-duty crates and industrial products with outdoor exposure",
    bis: "IS 7328-3B-MD-EDD",
    mfi: "7.5",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "7.5" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "22" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "190" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "24" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "800" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "50" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "850" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "67" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "122" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "132" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "62" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "185 – 235 °C" },
      { label: "Nozzle Temperature", value: "200 – 235 °C" },
    ],
    flags: ["Food contact", "UV / HALS", "Outdoor"],
  },
  {
    id: "b5500",
    name: "B5500",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Blow Molding (HMHDPE)",
    summary:
      "HMHDPE blow molding grade with exceptional processability, high rigidity, mechanical strength and impact resistance.",
    applications:
      "Medium bulk containers (~120 L) for chemicals, detergent, lube oils; water tanks up to 1000 L (add UV for outdoor)",
    bis: "IS 7328-3B-BB-FXTA",
    mfi: "0.06",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.952",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.06" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.35" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "8" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.952" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "27" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "40" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "64" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">1000" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "127" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "63" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "133" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 / 210 / 215 / 210 °C" },
      { label: "Die Temperature", value: "200 – 210 °C" },
      { label: "Parison Temperature", value: "190 – 210 °C" },
      { label: "Cooling Water for Mold", value: "20 – 25 °C" },
    ],
    flags: ["Food contact", "High ESCR", "HMHDPE"],
  },
  {
    id: "b6401",
    name: "B6401",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Blow Molding",
    summary:
      "HDPE blow molding grade combining exceptional processability with high rigidity, mechanical properties and impact resistance.",
    applications: "Up to 20 L containers for lubricants and edible oils",
    bis: "IS 7328-3P-BB-GXDA",
    mfi: "0.40",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.960",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.40" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.6" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "25" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.960" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "32" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "40" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "1000" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "300" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1300" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "68" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "<20" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "129" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "70" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "135" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "150 / 160 / 165 / 175 °C" },
      { label: "Die Temperature", value: "180 – 185 °C" },
      { label: "Parison Temperature", value: "185 – 190 °C" },
      { label: "Cooling Water for Mold", value: "20 – 25 °C" },
    ],
    flags: ["Food contact", "High rigidity"],
  },
  {
    id: "e5201",
    name: "E5201",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Blow / Extrusion / Film",
    summary:
      "Broad MWD HDPE with exceptional processability, high ESCR and excellent mechanical properties.",
    applications:
      "High ESCR blow molding, cable sheathing & jacketing, lamination film, GP film and extrusion",
    bis: "IS 7328-3B-BB-EXDA",
    mfi: "0.35",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.35" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.6" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "32" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "34" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "850" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "120" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">600" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "122" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "60" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "130" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "150 – 160 °C" },
      { label: "Die Temperature", value: "160 – 165 °C" },
      { label: "Parison Temperature", value: "160 – 170 °C" },
      { label: "Cooling Water for Mold", value: "20 – 25 °C" },
    ],
    flags: ["Food contact", "High ESCR", "Broad MWD"],
  },
  {
    id: "e5201s",
    name: "E5201S",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Blow / Pipe",
    summary:
      "Broad MWD HDPE for general-purpose blow molding, DWC pipes and general-purpose pipe.",
    applications: "General purpose blow molding, double-walled corrugated pipes, GP pipe",
    bis: "IS 7328-3B-BB-FXDA",
    mfi: "0.35",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.954",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.35" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.6" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "32" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.954" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "36" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "100" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1100" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "250" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "70" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "130" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "150 – 160 °C" },
      { label: "Die Temperature", value: "160 – 165 °C" },
      { label: "Parison Temperature", value: "165 – 170 °C" },
      { label: "Cooling Water for Mold", value: "20 – 25 °C" },
    ],
    flags: ["Food contact", "Pipe", "Broad MWD"],
  },
  {
    id: "f5400",
    name: "F5400",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Film (HMHDPE)",
    summary: "HMHDPE film grade with excellent processability and high mechanical strength.",
    applications: "General purpose film and very thin reinforced bag applications",
    bis: "IS 7328-3B-FB-FXTA",
    mfi: "0.09",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.952",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.09" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.50" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "14" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.952" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "28" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "40" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "180" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "950" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">500" },
      { label: "Dart Impact Strength", method: "ASTM D1709A", unit: "g", value: "80" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "124" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 220 °C" },
      { label: "BUR", value: "4 – 6" },
    ],
    flags: ["Food contact", "HMHDPE", "Film"],
  },
  {
    id: "hd-t6",
    name: "HD T6",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Extrusion / Lamination Film",
    summary:
      "General purpose extrusion and lamination film grade combining good processability with high mechanical strength.",
    applications: "Lamination films, woven sacks and tarpaulin",
    bis: "IS 7328-3P-FB-GXDA",
    mfi: "0.50",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.960",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.50" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.8" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "30" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.960" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "30" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "800" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "250" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1150" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "124" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 240 °C" },
      { label: "Die Temperature", value: "220 – 240 °C" },
      { label: "Quench Temperature", value: "25 °C" },
    ],
    flags: ["Food contact", "Lamination"],
  },
  {
    id: "m5600s",
    name: "M5600S",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Caps & Closures",
    summary:
      "Broad MWD HDPE for injection and compression molded CSD / beverage caps. Contains slip agent for torque release.",
    applications: "Caps & closures for CSD, water, juice and beverages",
    bis: "IS 7328-3B-CBF-FXDA",
    mfi: "0.7",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.954",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.7" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "2.7" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.954" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "26" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "75" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "950" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "750" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "68" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [{ label: "Barrel Temperature", value: "160 – 190 °C" }],
    flags: ["Food contact", "Slip agent", "High ESCR"],
  },
  {
    id: "m5601",
    name: "M5601",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Caps & Closures",
    summary:
      "Broad MWD HDPE for CSD / beverage caps. No slip agent. High ESCR and good organoleptics.",
    applications: "Caps & closures for CSD, water, juice and beverages",
    bis: "IS 7328-3B-CB-FXDA",
    mfi: "1.2",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.954",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.2" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "5.0" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.954" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "28" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "9.5" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "50" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "400" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "124" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "67" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [{ label: "Barrel Temperature", value: "160 – 190 °C" }],
    flags: ["Food contact", "No slip", "High ESCR"],
  },
  {
    id: "m5601s",
    name: "M5601S",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Caps & Closures",
    summary:
      "Broad MWD HDPE for CSD / beverage caps with slip agent for better torque release.",
    applications: "Caps & closures for CSD, water, juice and beverages",
    bis: "IS 7328-3B-CBF-FXDA",
    mfi: "1.2",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.954",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.2" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "5.0" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.954" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "28" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "9.5" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "50" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "400" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "124" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "67" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [{ label: "Barrel Temperature", value: "160 – 190 °C" }],
    flags: ["Food contact", "Slip agent", "High ESCR"],
  },
  {
    id: "m5818",
    name: "M5818",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Injection Molding",
    summary: "Injection molding HDPE combining excellent processability with good mechanical properties.",
    applications: "General purpose injection molded items",
    mfi: "19.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.956",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "19.0" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.956" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "24" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "350" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "36" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "64" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 235 °C" },
      { label: "Nozzle Temperature", value: "235 °C" },
    ],
    flags: ["High flow"],
  },
  {
    id: "p5100",
    name: "P5100",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Pipe (PE 80)",
    summary:
      "HDPE pipe grade with excellent processability, creep resistance, ESCR and mechanical properties.",
    applications: "PE 80 compliant pressure pipes",
    bis: "IS 7328-3B-PB-FXTA",
    mfi: "0.09",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.952",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.09" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.50" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "14" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.952" },
      { label: "Density (27°C, Annealed)", method: "IS 4984", unit: "g/cm³", value: "0.948" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "200" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">500" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "64" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
      { label: "Oxidative Induction Time", method: "ASTM D3895", unit: "min", value: ">30" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 180 °C" },
      { label: "Die Temperature", value: "170 – 190 °C" },
    ],
    flags: ["Food contact", "PE 80", "Pipe"],
  },
  {
    id: "p5200",
    name: "P5200",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Pipe (PE 63)",
    summary:
      "HDPE pipe grade with excellent processability, creep resistance, ESCR and mechanical properties.",
    applications: "PE 63 compliant pressure pipes",
    bis: "IS 7328-3B-PB-EXTA",
    mfi: "0.20",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.20" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.90" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "22" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Density (27°C, Annealed)", method: "IS 4984", unit: "g/cm³", value: "0.948" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "8" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "175" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">1000" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "123" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "64" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
      { label: "Oxidative Induction Time", method: "ASTM D3895", unit: "min", value: ">30" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "150 – 180 °C" },
      { label: "Die Temperature", value: "170 – 180 °C" },
    ],
    flags: ["Food contact", "PE 63", "Pipe", "High ESCR"],
  },
  {
    id: "p5200uv",
    name: "P5200UV",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Pipe / Telecom Duct (UV)",
    summary:
      "HALS-stabilized HDPE pipe grade for long outdoor service. Recommended for telecom ducts.",
    applications: "Telecom ducts and outdoor PE 63 pipe applications",
    bis: "IS 7328-3B-PD-EXTA",
    mfi: "0.20",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.20" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.90" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "20" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Density (27°C, Annealed)", method: "IS 4984", unit: "g/cm³", value: "0.948" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "8" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "175" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">1000" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "64" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
      { label: "Oxidative Induction Time", method: "ASTM D3895", unit: "min", value: ">30" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "150 – 180 °C" },
      { label: "Die Temperature", value: "170 – 180 °C" },
    ],
    flags: ["Food contact", "UV / HALS", "Telecom duct"],
  },
  {
    id: "p5300",
    name: "P5300",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Pipe (PE 100)",
    summary:
      "PE 100 pipe grade (MRS 10 MPa, ISO 9080 / ISO 12162) with high ESCR, creep resistance and RCP performance.",
    applications: "PE 100 pressure pipes",
    bis: "IS 7328-3B-PBK-EXTA",
    mfi: "0.05",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.950",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.05" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.25" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "9.5" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.950" },
      { label: "Density (27°C, Annealed)", method: "IS 4984", unit: "g/cm³", value: "0.948" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "26" },
      { label: "Elongation at Yield", method: "ASTM D638", unit: "%", value: "11" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "40" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "270" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: ">1000" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "125" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "70" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
      { label: "Oxidative Induction Time", method: "ASTM D3895", unit: "min", value: ">30" },
      { label: "RCP Critical Pressure (0°C)", method: "ISO 13477", unit: "bar", value: "≥10" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 220 °C" },
      { label: "Die Temperature", value: "180 – 220 °C" },
    ],
    flags: ["Food contact", "PE 100", "Pipe", "High ESCR"],
  },
  {
    id: "r5801",
    name: "R5801",
    family: "HDPE",
    brand: "Halene H",
    technology: "Mitsui CX",
    category: "Raffia / Stretched Tape",
    summary:
      "HDPE raffia grade combining excellent processability with high mechanical strength.",
    applications: "Stretched tape / raffia for woven sacks and tarpaulin",
    bis: "IS 7328-3P-TB-GXDA",
    mfi: "0.50",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.960",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "0.50" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.8" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "30" },
      { label: "Density (23°C, Annealed)", method: "ASTM D1505", unit: "g/cm³", value: "0.960" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "32" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "38" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "800" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "200" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1150" },
      { label: "Hardness", method: "ASTM D2240", unit: "Shore D", value: "65" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "124" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "131" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 240 °C" },
      { label: "Die Temperature", value: "220 – 240 °C" },
      { label: "Quench Temperature", value: "25 – 30 °C" },
    ],
    flags: ["Food contact", "Raffia"],
  },
];
