import type { Grade } from "./types";

export const lldpeGrades: Grade[] = [
  {
    id: "71501s",
    name: "71501S",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Blown Film",
    summary:
      "LLDPE blown film grade additivated with slip and anti-blocking agents for excellent openability.",
    applications: "General purpose packaging film",
    bis: "IS 7328-2B-FBH-BDA",
    mfi: "1.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.922",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "2.6" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "23" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.922" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "126" },
      { label: "Tensile at Yield MD / TD", method: "ASTM D882", unit: "MPa", value: "10 / 10" },
      { label: "Tensile at Break MD / TD", method: "ASTM D882", unit: "MPa", value: "25 / 16" },
      { label: "Elongation at Break MD / TD", method: "ASTM D882", unit: "%", value: "650 / 750" },
      { label: "Elmendorf Tear MD / TD", method: "ASTM D1922", unit: "g/μ", value: "6 / 16" },
      { label: "Dart Impact F50", method: "ASTM D1709A", unit: "g/μ", value: "4.0" },
      { label: "Gloss at 60°", method: "ASTM D2457", unit: "GU", value: "76" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 200 °C" },
      { label: "Melt Temperature", value: "190 – 210 °C" },
      { label: "Blow up Ratio", value: "2.0 – 3.0" },
      { label: "Die Gap", value: "2.0 – 2.5 mm" },
    ],
    flags: ["Food contact", "Slip + antiblock", "Film"],
  },
  {
    id: "71601d",
    name: "71601D",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Drip Lateral Pipe",
    summary:
      "LLDPE additivated for excellent processability in drip lateral pipes, with controlled morphology.",
    applications: "Drip lateral pipes",
    bis: "IS 7328-2B-NB-BDA",
    mfi: "1.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.920",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "2.8" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "23" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.920" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "30" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "1000" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "400" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "1000" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "125" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 240 °C" },
      { label: "Die Temperature", value: "240 – 250 °C" },
    ],
    flags: ["Food contact", "Drip irrigation", "High ESCR"],
  },
  {
    id: "71601w",
    name: "71601W",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Blown Film / Lamination",
    summary:
      "LLDPE blown film grade without slip or antiblocking additives, for adhesive lamination films.",
    applications: "General purpose adhesive lamination films",
    bis: "IS 7328-2B-FBE-BDA",
    mfi: "1.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.920",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "1.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "2.6" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "23" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.920" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "125" },
      { label: "Tensile at Yield MD / TD", method: "ASTM D882", unit: "MPa", value: "10 / 10" },
      { label: "Tensile at Break MD / TD", method: "ASTM D882", unit: "MPa", value: "25 / 16" },
      { label: "Elongation at Break MD / TD", method: "ASTM D882", unit: "%", value: "650 / 750" },
      { label: "Elmendorf Tear MD / TD", method: "ASTM D1922", unit: "g/μ", value: "6 / 16" },
      { label: "Dart Impact F50", method: "ASTM D1709A", unit: "g/μ", value: "4.0" },
      { label: "Gloss at 60°", method: "ASTM D2457", unit: "GU", value: "76" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 200 °C" },
      { label: "Melt Temperature", value: "190 – 210 °C" },
      { label: "Blow up Ratio", value: "2.0 – 3.0" },
      { label: "Die Gap", value: "2.0 – 2.5 mm" },
    ],
    flags: ["Food contact", "No slip", "Lamination"],
  },
  {
    id: "71602s",
    name: "71602S",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Blown Film",
    summary:
      "Higher-flow LLDPE blown film grade with slip and antiblock for good openability.",
    applications: "General purpose packaging film",
    bis: "IS 7328-2B-FBH-BDB",
    mfi: "2.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.920",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "2.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "6.0" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "60" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.920" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "125" },
      { label: "Tensile at Yield MD / TD", method: "ASTM D882", unit: "MPa", value: "11 / 10" },
      { label: "Tensile at Break MD / TD", method: "ASTM D882", unit: "MPa", value: "19 / 14" },
      { label: "Elongation at Break MD / TD", method: "ASTM D882", unit: "%", value: "700 / 750" },
      { label: "Elmendorf Tear MD / TD", method: "ASTM D1922", unit: "g/μ", value: "4 / 12" },
      { label: "Dart Impact F50", method: "ASTM D1709A", unit: "g/μ", value: "3" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "170 – 200 °C" },
      { label: "Melt Temperature", value: "190 – 200 °C" },
      { label: "Blow up Ratio", value: "2.0 – 3.0" },
      { label: "Die Gap", value: "2.0 – 2.5 mm" },
    ],
    flags: ["Food contact", "Slip + antiblock", "Film"],
  },
  {
    id: "71602w",
    name: "71602W",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Blown Film",
    summary:
      "Higher-flow LLDPE film grade without slip or antiblock, for general purpose packaging film.",
    applications: "General purpose packaging film",
    bis: "IS 7328-2B-FBE-BDB",
    mfi: "2.5",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.920",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "2.5" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "6.5" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "60" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.920" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "125" },
      { label: "Tensile at Yield MD / TD", method: "ASTM D882", unit: "MPa", value: "12 / 11" },
      { label: "Tensile at Break MD / TD", method: "ASTM D882", unit: "MPa", value: "23 / 19" },
      { label: "Elongation at Break MD / TD", method: "ASTM D882", unit: "%", value: "500 / 750" },
      { label: "Elmendorf Tear MD / TD", method: "ASTM D1922", unit: "g/μ", value: "2.5 / 11" },
      { label: "Dart Impact F50", method: "ASTM D1709A", unit: "g/μ", value: "2" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "170 – 200 °C" },
      { label: "Melt Temperature", value: "190 – 200 °C" },
      { label: "Blow up Ratio", value: "2.0 – 3.0" },
      { label: "Die Gap", value: "2.0 – 2.5 mm" },
    ],
    flags: ["Food contact", "No slip", "Film"],
  },
  {
    id: "72307e",
    name: "72307E",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Extrusion Coating",
    summary:
      "High-flow LLDPE for extrusion coating on woven fabric, aluminium foil, jute, paper and allied substrates.",
    applications: "Extrusion coating on HDPE woven fabric, foil, jute, paper",
    bis: "IS 7328-2B-HB-CDD",
    mfi: "7.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.926",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "7.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "19.0" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "165" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.926" },
      { label: "Tensile Strength at Break", method: "ASTM D638", unit: "MPa", value: "18" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "500" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "300" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "102" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "126" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "200 – 270 °C" },
      { label: "Die Temperature", value: "250 – 280 °C" },
    ],
    flags: ["Food contact", "Coating", "High flow"],
  },
  {
    id: "73005t",
    name: "73005T",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Roto Molding",
    summary:
      "LLDPE roto molding grade with a balanced processability / mechanics profile for tanks and containers.",
    applications: "Tanks and containers for domestic & industrial water storage, sanitation, agriculture",
    bis: "IS 7328-2B-RBJ-CDC",
    mfi: "5.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.934",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "5.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "14" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "120" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.934" },
      { label: "Density range (IS 2530)", method: "IS 2530", unit: "g/cm³", value: "0.932 – 0.936" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "17" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "800" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "350" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "400" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "110" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "126" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "100" },
    ],
    processing: [{ label: "Oven Temperature", value: "240 – 280 °C" }],
    flags: ["Food contact", "Roto molding"],
  },
  {
    id: "73005tu",
    name: "73005TU",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Roto Molding (UV)",
    summary:
      "UV-stabilized (~2000 ppm light stabilizer) LLDPE roto grade for outdoor tanks and containers.",
    applications: "Outdoor tanks and containers with UV stability for water, sanitation, agriculture",
    bis: "IS 7328-2B-RDO-CDC",
    mfi: "5.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.934",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "5.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "14" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "120" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.934" },
      { label: "Density range (IS 2530)", method: "IS 2530", unit: "g/cm³", value: "0.932 – 0.936" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "17" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "800" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "350" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "400" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "110" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "126" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "100" },
    ],
    processing: [{ label: "Oven Temperature", value: "240 – 280 °C" }],
    flags: ["Food contact", "UV stabilized", "Roto molding"],
  },
  {
    id: "73204t",
    name: "73204T",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Roto Molding",
    summary:
      "Lower-density LLDPE roto grade with higher impact and ESCR for tanks and containers.",
    applications: "Tanks and containers for domestic & industrial water storage, sanitation, agriculture",
    bis: "IS 7328-2B-RBO-CDC",
    mfi: "5.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.932",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "5.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "14" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "120" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.932" },
      { label: "Density range (IS 2530)", method: "IS 2530", unit: "g/cm³", value: "0.932 – 0.934" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "17" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "850" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "400" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "109" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "126" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "500" },
    ],
    processing: [{ label: "Oven Temperature", value: "240 – 280 °C" }],
    flags: ["Food contact", "Roto molding", "High ESCR"],
  },
  {
    id: "73204tu",
    name: "73204TU",
    family: "LLDPE",
    brand: "Halene L",
    technology: "Spherilene",
    category: "Roto Molding (UV)",
    summary:
      "UV-stabilized (~2000 ppm) lower-density LLDPE roto grade for outdoor tanks with high impact and ESCR.",
    applications: "Outdoor tanks and containers with UV stability for water, sanitation, agriculture",
    bis: "IS 7328-2B-RDO-CDC",
    mfi: "5.0",
    mfiCondition: "2.16 kg, 190°C",
    density: "0.932",
    properties: [
      { label: "MFI (2.16 kg)", method: "ASTM D1238", unit: "g/10 min", value: "5.0" },
      { label: "MFI (5 kg)", method: "ASTM D1238", unit: "g/10 min", value: "14" },
      { label: "MFI (21.6 kg)", method: "ASTM D1238", unit: "g/10 min", value: "120" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.932" },
      { label: "Density range (IS 2530)", method: "IS 2530", unit: "g/cm³", value: "0.932 – 0.934" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "17" },
      { label: "Elongation at Break", method: "ASTM D638", unit: "%", value: "850" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "400" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "109" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "126" },
      { label: "ESCR (F50, 10% Igepal)", method: "ASTM D1693B", unit: "hr", value: "500" },
    ],
    processing: [{ label: "Oven Temperature", value: "240 – 280 °C" }],
    flags: ["Food contact", "UV stabilized", "High ESCR"],
  },
];
