import type { Grade } from "./types";

export const ppGrades: Grade[] = [
  {
    id: "b202s",
    name: "B202S",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Random Copolymer / Blow",
    summary:
      "PP random copolymer with exceptional processability, melt strength, high clarity and gloss.",
    applications: "Blow molded bottles and containers for medical and transparent products",
    bis: "IS 10951-2-BB-A",
    mfi: "1.9",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "1.9" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "27" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "11" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "90" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "130" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "68" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 210 °C" },
      { label: "Die Temperature", value: "190 – 210 °C" },
    ],
    flags: ["Food contact", "Random copolymer", "Clarity"],
  },
  {
    id: "m212s",
    name: "M212S",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Clarified Random Copolymer",
    summary:
      "Clarified PP random copolymer with high flow, low cycle time and stiffness–impact balance.",
    applications: "High-clarity IM and ISBM containers, household items, injection syringes",
    bis: "IS 10951-2-MBL-C",
    mfi: "12",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "12" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "28" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "12" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1050" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "50" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "128" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "75" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 250 °C" },
      { label: "Mold Temperature", value: "30 – 60 °C" },
    ],
    flags: ["Food contact", "Clarified", "ISBM"],
  },
  {
    id: "m304",
    name: "M304",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Impact Copolymer",
    summary:
      "Heterophasic PP impact copolymer with low cycle time and excellent impact–stiffness balance.",
    applications: "Injection molded furniture, automotive components, paint pails, crates",
    bis: "IS 10951-3-MB-A",
    mfi: "3.5",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "3.5" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: ">150" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "90" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Impact copolymer"],
  },
  {
    id: "m307",
    name: "M307",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Impact Copolymer",
    summary: "Heterophasic PP impact copolymer combining excellent processability with low cycle time.",
    applications: "General purpose injection molding",
    bis: "IS 10951-3-MB-B",
    mfi: "7",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "7" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "23" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "6" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "950" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "80" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "88" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Impact copolymer"],
  },
  {
    id: "m310",
    name: "M310",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Impact Copolymer",
    summary:
      "High-flow heterophasic PP ICP with thermal stability and good impact–stiffness balance.",
    applications: "Injection molded battery boxes and industrial items",
    bis: "IS 10951-3-JB-C",
    mfi: "10",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "10" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "24" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "6" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1200" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "90" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "100" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 250 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Battery box"],
  },
  {
    id: "m311t",
    name: "M311T",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Impact Copolymer",
    summary:
      "High-toughness heterophasic PP ICP with high flow, gloss, and 500 J/m Izod impact.",
    applications: "Automotive components, compounds, molded luggage, industrial parts",
    bis: "IS 10951-3-MB-C",
    mfi: "10",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "10" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "21" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "900" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "142" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "85" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 250 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "High impact"],
  },
  {
    id: "m312",
    name: "M312",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Impact Copolymer",
    summary:
      "High-flow heterophasic PP ICP with good impact–stiffness balance and gloss.",
    applications: "Automotive components, housewares, luggage, paint pails, compounds",
    bis: "IS 10951-3-MB-C",
    mfi: "12",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "12" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "23" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "5" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "950" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "120" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "100" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 250 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Impact copolymer"],
  },
  {
    id: "m320",
    name: "M320",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Nucleated Impact Copolymer",
    summary:
      "Nucleated heterophasic PP ICP with low cycle time and good impact–stiffness balance.",
    applications: "Injection molded products, automotive components, appliances",
    bis: "IS 10951-3-MBV-D",
    mfi: "20",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "20" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "23" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "6" },
      { label: "Flexural Modulus (1% Secant)", method: "ASTM D790A", unit: "MPa", value: "1150" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "100" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "105" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "165" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Nucleated"],
  },
  {
    id: "m325",
    name: "M325",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Impact Copolymer",
    summary:
      "High-flow heterophasic PP ICP with stiffness–impact balance and gloss.",
    applications:
      "Furniture, compounds, automotive, housewares, appliance parts, extrusion coating",
    bis: "IS 10951-3-ZB-D",
    mfi: "25",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "25" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "25" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1150" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "60" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "140" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "84" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "165" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 210 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "High flow"],
  },
  {
    id: "m330",
    name: "M330",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Nucleated Impact Copolymer",
    summary: "Nucleated heterophasic PP ICP, MFI 30, for fast-cycle injection molding.",
    applications: "Injection molded products, automotive parts, compounds, appliances",
    bis: "IS 10951-3-MBV-D",
    mfi: "30",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "30" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "22" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "6" },
      { label: "Flexural Modulus (1% Secant)", method: "ASTM D790A", unit: "MPa", value: "1100" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "100" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "100" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "165" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Nucleated", "High flow"],
  },
  {
    id: "m340",
    name: "M340",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Nucleated Impact Copolymer",
    summary: "Nucleated heterophasic PP ICP, MFI 40, for fast-cycle injection molding.",
    applications: "Injection molded products, automotive parts, compounds, appliances",
    bis: "IS 10951-3-MBV-E",
    mfi: "40",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "40" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "22" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "6" },
      { label: "Flexural Modulus (1% Secant)", method: "ASTM D790A", unit: "MPa", value: "1050" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "90" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "100" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "165" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Nucleated", "High flow"],
  },
  {
    id: "m365",
    name: "M365",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Nucleated Impact Copolymer",
    summary:
      "Very high-flow nucleated heterophasic PP ICP for thin-walled injection molding.",
    applications: "Thin-walled IM products, automotive parts, compounds, appliances",
    bis: "IS 10951-3-MBV-F",
    mfi: "65",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "65" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "22" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "6" },
      { label: "Flexural Modulus (1% Secant)", method: "ASTM D790A", unit: "MPa", value: "1200" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "75" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "148" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "95" },
      { label: "DSC Melting Temperature", method: "ASTM D3418", unit: "°C", value: "165" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Nucleated", "Thin wall"],
  },
  {
    id: "m308s",
    name: "M308S",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "High Impact Copolymer",
    summary:
      "High-impact heterophasic PP ICP with low cycle time and excellent impact–stiffness balance.",
    applications: "Automotive components, housewares, luggage, paint pails, compounds",
    bis: "IS 10951-3-MB-B",
    mfi: "8",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "8" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "20" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "5" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1000" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "500" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "145" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "90" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "160 – 250 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "High impact"],
  },
  {
    id: "f103",
    name: "F103",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / BOPP Film",
    summary:
      "PP homopolymer designed for stable stenter extrusion with low water carryover and good thickness control.",
    applications: "BOPP films for food packaging, lamination and metallizable applications",
    bis: "IS 10951-1-FB-A",
    mfi: "3",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "34" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "10" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1450" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "40" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "152" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "95" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "230 – 280 °C" },
      { label: "Water Bath Temperature", value: "10 – 15 °C" },
    ],
    flags: ["Food contact", "BOPP", "Homopolymer"],
  },
  {
    id: "f110",
    name: "F110",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / TQ Film",
    summary:
      "PP homopolymer with slip and antiblock for tubular quenched film; excellent clarity and gloss.",
    applications: "TQ film for packaging foodstuffs and garments",
    bis: "IS 10951-1-NBH-C",
    mfi: "11",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "11" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "34" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1400" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "30" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "154" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "99" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 230 °C" },
      { label: "Die Temperature", value: "190 – 210 °C" },
    ],
    flags: ["Food contact", "TQ film", "Slip + antiblock"],
  },
  {
    id: "f135",
    name: "F135",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / Coating & Spunbond",
    summary:
      "Controlled-rheology PP homopolymer with high MFI, narrow MWD and gas-fading resistance.",
    applications: "Extrusion coating on woven fabrics; spunbond nonwoven and hygiene products",
    bis: "IS 10951-1-HBV-E",
    mfi: "35",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "35" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "35" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "8" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1350" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "45" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "150" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "105" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 220 °C" },
      { label: "Die Temperature", value: "215 – 220 °C" },
    ],
    flags: ["Food contact", "Spunbond", "Controlled rheology"],
  },
  {
    id: "m103",
    name: "M103",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / IM & Extrusion",
    summary: "PP homopolymer combining easy processability with high strength.",
    applications: "General purpose extrusion and injection molding",
    bis: "IS 10951-1-MB-A",
    mfi: "3",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "32" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1300" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "35" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "153" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "93" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "190 – 250 °C" },
      { label: "Mold Temperature", value: "40 – 50 °C" },
    ],
    flags: ["Food contact", "Homopolymer"],
  },
  {
    id: "m106",
    name: "M106",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / IM & Extrusion",
    summary: "PP homopolymer combining easy processability with high strength.",
    applications: "General purpose extrusion and injection molding",
    bis: "IS 10951-1-MB-A",
    mfi: "6",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "6" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "32" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1300" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "35" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "153" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "93" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Homopolymer"],
  },
  {
    id: "m108",
    name: "M108",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / IM & Extrusion",
    summary: "PP homopolymer combining easy processability with high strength.",
    applications: "General purpose extrusion and injection molding",
    bis: "IS 10951-1-MB-B",
    mfi: "8",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "8" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "30" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "7" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1300" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "35" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "152" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "94" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 260 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "Homopolymer"],
  },
  {
    id: "m110",
    name: "M110",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / Injection",
    summary:
      "PP homopolymer with low cycle time, high gloss and excellent color for furniture and housewares.",
    applications: "Injection molded furniture and household items",
    bis: "IS 10951-1-MB-C",
    mfi: "11",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "11" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "34" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1500" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "30" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "154" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "99" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "180 – 280 °C" },
      { label: "Mold Temperature", value: "30 – 40 °C" },
    ],
    flags: ["Food contact", "High gloss"],
  },
  {
    id: "r103",
    name: "R103",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / Raffia",
    summary:
      "PP homopolymer with low water carryover, excellent strength and color for raffia.",
    applications: "Stretched tape raffia for woven sacks, FIBC, ropes and yarns",
    bis: "IS 10951-1-TB-A",
    mfi: "3",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "3" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "34" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "9" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1500" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "40" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "153" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "93" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "220 – 280 °C" },
      { label: "Die Temperature", value: "260 – 280 °C" },
      { label: "Quench Temperature", value: "30 – 40 °C" },
      { label: "Stretching Temperature", value: "~ 160 °C (Oven)" },
    ],
    flags: ["Food contact", "Raffia"],
  },
  {
    id: "t103",
    name: "T103",
    family: "PP",
    brand: "Halene P",
    technology: "Spheripol",
    category: "Homopolymer / Thermoforming",
    summary:
      "PP homopolymer with exceptional stiffness, clarity and gloss for thermoforming.",
    applications: "Thermoforming of cups, containers and miscellaneous disposable items",
    bis: "IS 10951-1-DBL-A",
    mfi: "4",
    mfiCondition: "2.16 kg, 230°C",
    density: "0.90",
    properties: [
      { label: "MFI (2.16 kg, 230°C)", method: "ASTM D1238", unit: "g/10 min", value: "4" },
      { label: "Density (23°C)", method: "ASTM D1505", unit: "g/cm³", value: "0.90" },
      { label: "Tensile Strength at Yield", method: "ASTM D638", unit: "MPa", value: "37" },
      { label: "Tensile Elongation at Yield", method: "ASTM D638", unit: "%", value: "8" },
      { label: "Flexural Modulus", method: "ASTM D790A", unit: "MPa", value: "1700" },
      { label: "Notched Izod (23°C)", method: "ASTM D256A", unit: "J/m", value: "60" },
      { label: "Vicat Softening Point (10 N)", method: "ASTM D1525", unit: "°C", value: "154" },
      { label: "HDT (0.455 MPa)", method: "ASTM D648", unit: "°C", value: "95" },
    ],
    processing: [
      { label: "Barrel Temperature", value: "190 – 230 °C" },
      { label: "Die Temperature", value: "220 – 250 °C" },
    ],
    flags: ["Food contact", "Thermoforming", "High stiffness"],
  },
];
